# Generated by Django 5.2 on 2025-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNewInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('device_type', models.CharField(choices=[('Laptop/Desktop', 'Laptop/Desktop'), ('TV', 'TV'), ('Mobile', 'Mobile'), ('CCTV', 'CCTV')], max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('price', models.CharField(default='TBD', max_length=10)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('progress', 'In Progress'), ('closed', 'Closed')], default='opened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('device_type', models.CharField(max_length=50)),
                ('issue_description', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('progress', 'In Progress'), ('closed', 'Closed')], default='opened', max_length=20)),
            ],
        ),
    ]
