# Generated by Django 5.2 on 2025-04-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buynewinquiry',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buynewinquiry',
            name='state',
        ),
    ]
