# Generated by Django 5.2 on 2025-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_buynewinquiry_city_remove_buynewinquiry_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynewinquiry',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buynewinquiry',
            name='state',
            field=models.CharField(default='Not specified', max_length=50),
            preserve_default=False,
        ),
    ]
